import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import { ErrorBoundary } from 'next/dist/client/components/error-boundary';
import Error from './error';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<header>
					<nav className="flex items-center justify-between bg-black text-white rounded-4xl mx-4 px-6 py-4 my-2">
						<div>
							<h2>
								<Link href={'/'}>Blogs</Link>
							</h2>
						</div>
						<ul className="flex items-center gap-4">
							<li>
								<Link href={'/users'}>Users</Link>
							</li>
							<li>
								<Link href={'/posts'}>Posts</Link>
							</li>
						</ul>
					</nav>
				</header>
				<ErrorBoundary fallback={<Error />}>{children}</ErrorBoundary>
				<footer className="bg-black text-white py-5 mt-10">
					<div className="flex justify-center items-center my-6 ">
						<h3 className="text-5xl font-bold">New Blog Website</h3>
					</div>

					<div className="flex justify-center py-2">
						<small>© copyrights resereved</small>
					</div>
				</footer>
			</body>
		</html>
	);
}
